asc-community/AngouriMath

AngouriMath/AngouriMath.csproj, AngouriMath/Core/Sys/Items/Tensors/Tensors.cs
=> Revert to .NET Standard 2.0

AngouriMath/Functions/Algebra/Solver/Analytical/AnalyticalSolver.cs, AngouriMath/Functions/Algebra/Solver/Analytical/TrigonometricSolver.cs, Samples/Samples/Program.cs, Tests/UnitTests/Algebra/SolveTest/SolveOneEquation.cs
probably some code need refactoring, but it is a working solution
=> added linear trig solver

AngouriMath/Core/Sys/Sets/SetNode.cs, AngouriMath/Functions/Output/Latex.cs
=> Set LaTeXising

AngouriMath/AngouriMath.csproj
=> Don't need "call"

AngouriMath/Core/Sys/Items/Number.cs, AngouriMath/Functions/Output/Latex.cs
=> LaTeXize infinity and tensors correctly

AngouriMath/Functions/Output/Latex.cs
Continuation of https://github.com/asc-community/AngouriMath/pull/94
=> Fix LaTeX for real intervals

.github/workflows/Test.yml, AngouriMath/Core/Sys/Items/Numeric/ComplexNumber/ComplexNumberOperators.cs, AngouriMath/Core/Sys/Items/Numeric/ComplexNumber/RealNumber/RealNumber.cs, AngouriMath/Functions/Output/Latex.cs, Tests/UnitTests/Convenience/LatexTest.cs
https://github.com/asc-community/AngouriMath/pull/127#issuecomment-640194973
=> "I recommend writing tests for it to make sure it works correctly"

AngouriMath/Convenience/MathS.cs, AngouriMath/Core/Sys/Items/Numeric/NumberOperators.cs, AngouriMath/Functions/Algebra/EquationSolver/Analytical/AnalyticalSolver.cs, AngouriMath/Functions/Algebra/EquationSolver/Analytical/CommonDenominatorSolver.cs, Samples/Samples/Program.cs, Tests/UnitTests/Algebra/SolveTest/SolveOneEquation.cs
Solver for cases such as (x - a) / (x + b) + c and other where denominators have mention of x is implemented
=> Fraction equalities solver

AngouriMath/Core/Sys/Entity/Entity.cs, AngouriMath/Core/Sys/Entity/Operations.cs, AngouriMath/Core/Sys/Items/Numeric/ComplexNumber.cs, AngouriMath/Core/Sys/Items/Numeric/Number.cs, AngouriMath/Core/Sys/Items/Numeric/RealNumber.cs, AngouriMath/Functions/Output/Latex.cs, AngouriMath/Functions/Output/ToString.cs, Tests/UnitTests/Convenience/LatexTest.cs
You merged before I could push lol
Fixes #148
=> Address comments and remove unused code

AngouriMath/AngouriMath.csproj, AngouriMath/Convenience/SynonymFunctions.cs, AngouriMath/Core/Sys/Entity/Entity.cs, AngouriMath/Core/Sys/Items/Tensors/TensorFunctional.cs, AngouriMath/Core/TreeAnalysis/Search/Search.cs, AngouriMath/Functions/Algebra/EquationSolver/Analytical/AnalyticalSolver.cs, AngouriMath/Functions/Algebra/EquationSolver/Analytical/PolynomialSolver.cs, AngouriMath/Functions/Evaluation/Simplification/Simplificator.cs, AngouriMath/Functions/Evaluation/Simplification/SmartPolynomialCollapser.cs, AngouriMath/Functions/Utils/Utils.cs, Samples/Samples/Program.cs
An entity now has a parent, also migrated to new GT, and what is more important, an attempt to improve simplifier was taken. Unfortunately, it still requires a lot of work, and the algorithm will not be there by 1.1.0.5
=> Entity parent

AngouriMath/Functions/Continuous/Limits/Limit.Definition.cs, AngouriMath/Functions/Evaluation/Patterns/Patterns.Sets.cs, AngouriMath/Functions/Evaluation/Simplificator.cs, AngouriMath/Functions/Substitute.cs, README.md, Tests/UnitTests/Calculus/Limits.cs, Tests/UnitTests/Common/SubstituteTest.cs, Tests/UnitTests/PatternsTest/SetSimplify.cs
And equivalence table for limits
=> Bugs fixing

.github/workflows/Benchmark.yml, .github/workflows/Build.yml, .github/workflows/Test.yml, AngouriMath/Convenience/AngouriMathExtensions.cs, AngouriMath/Functions/Output/ToString.Classes.cs, README.md, Samples/SampleNet5/Program.cs, Samples/Samples/Program.cs, Tests/UnitTests/Common/CircleTest.cs, Tests/UnitTests/Core/Numeric.cs
=> Minor mistakes fixes

AngouriMath/Functions/Simplification/Patterns/Patterns.Trigonometry.cs, AngouriMath/Functions/TreeAnalyzer/Sort.Classes.cs, AngouriMath/Functions/TreeAnalyzer/Sort.Definition.cs, Tests/UnitTests/PatternsTest/SimplifyTest.cs, Tests/UnitTests/PatternsTest/SortSimplifyTest.cs
String ids for entities reconsidered to fit a better grouping
=> New sorter

AngouriMath/Convenience/MathS.cs, AngouriMath/Core/Entity/Continuous/Entity.Continuous.Integer.Definition.cs, AngouriMath/Functions/NumbersExtensions.cs, Samples/Samples/Program.cs, Tests/UnitTests/Convenience/ExtensionTest.cs
Add Phi, CountDivisors and Factorization functions.
=> Add several things for number theory.

Sources/AngouriMath/Core/Compilation/Compiler.cs, Sources/AngouriMath/Core/Compilation/FastExpression.cs, Sources/AngouriMath/Core/Entity/Continuous/Entity.Continuous.Rational.Definition.cs, Sources/AngouriMath/Core/Entity/Continuous/Number/Operators.cs, Sources/AngouriMath/Core/Entity/Omni/Entity.Tensor.cs, Sources/AngouriMath/Core/Exceptions/AngouriMathBaseException.cs, Sources/AngouriMath/Core/Exceptions/SysExceptions.cs, Sources/AngouriMath/Core/Exceptions/UserInputInvalidException.cs, Sources/AngouriMath/Docs/Usage/Exceptions.md, Sources/AngouriMath/Docs/WhatsNew/1.2.0.0.md, Sources/AngouriMath/Functions/Boolean/TableSolver.cs, Sources/AngouriMath/Functions/Continuous/Limits/Limit.Definition.cs, Sources/AngouriMath/Functions/Continuous/Solvers/EquationSolver/AnalyticalEquationSolver.cs, Sources/AngouriMath/Functions/Continuous/Solvers/EquationSolver/InvertNode.Classes.cs, Sources/AngouriMath/Functions/Evaluation/Evaluation.Continuous.Definition.cs, Sources/AngouriMath/Functions/Evaluation/Evaluation.Definition.cs, Sources/AngouriMath/Functions/Evaluation/Evaluation.Discrete.Definition.cs, Sources/AngouriMath/Functions/NumbersExtensions.cs, Sources/AngouriMath/Functions/Output/ToString.Classes.cs, Sources/AngouriMath/Functions/Output/ToSympy.Classes.cs, Sources/Samples/Samples/Program.cs, Sources/Tests/UnitTests/PatternsTest/TableTrigConstTest.cs
So that it would be even more convenient to work with exceptions
=> Ultimate base class added, ArgumentException removed

Sources/AngouriMath/AngouriMath.csproj, Sources/AngouriMath/Convenience/MathS.cs, Sources/AngouriMath/Core/Entity/Omni/Entity.Matrix.cs, Sources/Samples/Samples/Program.cs, Sources/Tests/UnitTests/Algebra/MatrixTest.cs
This should close a number of issues for matrices
=> Matrices improvements

Sources/AngouriMath/Core/Entity/Continuous/Entity.Continuous.Complex.Definition.cs, Sources/AngouriMath/Core/Entity/Continuous/Number/Operators.cs
=> Convert Conjugate method to property

Sources/AngouriMath/Convenience/MathS.cs, Sources/Tests/UnitTests/Algebra/MatrixTest.cs
=> Matrix index->entity API

Sources/Tests/FSharpWrapperUnitTests/FSharpWrapperUnitTests.fsproj, Sources/Tests/FSharpWrapperUnitTests/Functions.Matrices.fs, Sources/Tests/FSharpWrapperUnitTests/Utils.fs, Sources/Wrappers/AngouriMath.FSharp/AngouriMath.FSharp.fsproj, Sources/Wrappers/AngouriMath.FSharp/Core.fs, Sources/Wrappers/AngouriMath.FSharp/MatrixOperators.fs
=> Easy API for matrices

Sources/AngouriMath/Convenience/MathS.cs, Sources/AngouriMath/Functions/Series.cs, Sources/Tests/UnitTests/Calculus/SeriesTest.cs
Adds https://github.com/asc-community/AngouriMath/issues/436
=> Multivariable Taylor Polynomials

Sources/Tests/FSharpWrapperUnitTests/Functions.Matrices.fs, Sources/Wrappers/AngouriMath.FSharp/Matrices.fs
See https://github.com/asc-community/AngouriMath/issues/389
=> Adds det, adjugate, and inverse

Sources/AngouriMath/Convenience/MathS.cs, Sources/AngouriMath/Functions/Series.cs, Sources/Tests/UnitTests/Calculus/SeriesTest.cs
API improvements described in https://github.com/asc-community/AngouriMath/issues/449
=> Better Taylor function naming

Sources/AngouriMath/AngouriMath.csproj, Sources/AngouriMath/Core/Entity/Continuous/Entity.Continuous.Complex.Definition.cs, Sources/AngouriMath/Core/Entity/Continuous/Entity.Continuous.Rational.Definition.cs, Sources/AngouriMath/Core/Entity/Entity.Definition.cs, Sources/AngouriMath/Core/Entity/Omni/Entity.Matrix.cs, Sources/AngouriMath/Core/Entity/Omni/Entity.Omni.Classes.cs, Sources/AngouriMath/Functions/Evaluation/Evaluation.Definition.cs, Sources/Tests/UnitTests/Core/Multithreading/CancelTest.cs, Sources/Tests/UnitTests/Core/Multithreading/MultithreadingCancel.cs
=> Moved to the release version of Honk#

Sources/AngouriMath/Convenience/MathS.cs
=> Exposing sine and cosine expansion algos to MathS.Compute

Sources/Tests/FSharpWrapperUnitTests/Functions.Continuous.fs, Sources/Wrappers/AngouriMath.FSharp/Functions.fs
This is for https://github.com/asc-community/AngouriMath/issues/428 , but I have only done this for continuous functions because it's sort of unclear.
=> Continuous function InnerSimplified

Sources/Tests/InteractiveWrapperUnitTests/AggressiveOperators.fs, Sources/Wrappers/AngouriMath.Interactive/AggressiveOperators.fs, Sources/Wrappers/AngouriMath.Interactive/AngouriMath.Interactive.fsproj
Should close #401 . Does this need complete unit testing?
=> Some operators for Interactive

Sources/Analyzers/Analyzers/StaticFieldThreadSafety.cs, Sources/AngouriMath/Core/CoreAttributes.cs, Sources/AngouriMath/Functions/NumberTheory/Primes.cs, Sources/Tests/InteractiveWrapperUnitTests/InteractiveWrapperUnitTests.fsproj, Sources/Wrappers/AngouriMath.Interactive/AngouriMath.Interactive.fsproj, Sources/Wrappers/AngouriMath.Interactive/Repack.ps1
=> Deps update

.gitignore, Sources/Samples/Samples/Program.cs, Sources/Tests/FSharpWrapperUnitTests/Functions.Matrices.fs, Sources/Tests/FSharpWrapperUnitTests/MatricesTest.fs, Sources/Wrappers/AngouriMath.FSharp/Matrices.fs
=> Priority fix

Sources/AngouriMath/AngouriMath.csproj, Sources/AngouriMath/Functions/Compilation/Compile.Linq.Definition.cs, Sources/AngouriMath/Functions/Compilation/IntoLinq/MathAllMethods.tt, Sources/Samples/Samples/Program.cs
So that net472 to be natively supported. Also, fewer dependencies on ns2.1
=> Multitargeting

Sources/AngouriMath/AngouriMath.csproj, Sources/Tests/InteractiveWrapperUnitTests/HtmlOutput.fs, Sources/Wrappers/AngouriMath.Interactive/KernelExtension.fs
=> Formatters for PeterO Numbers

Sources/AngouriMath/AngouriMath/Functions/Compilation/IntoLinq/CompilationProtocol.cs, Sources/Terminal/AngouriMath.Terminal.Lib/FSharpInteractive.fs, Sources/Tests/UnitTests/Common/CompilationIntoLinqTest.cs
=> Fixes of the terminal and compilation protocol

.github/workflows/InteractiveTest.yml, Sources/Samples/InteractivePlayground/Program.fs, Sources/Terminal/AngouriMath.Terminal.Lib/AngouriMath.Terminal.Lib.fsproj, Sources/Terminal/AngouriMath.Terminal.Lib/FSharpInteractive.fs, Sources/Terminal/AngouriMath.Terminal/AngouriMath.Terminal.fsproj, Sources/Tests/InteractiveWrapperUnitTests/InteractiveWrapperUnitTests.fsproj, Sources/Tests/TerminalUnitTests/TerminalUnitTests.fsproj, Sources/Wrappers/AngouriMath.Interactive/AngouriMath.Interactive.fsproj, Sources/Wrappers/AngouriMath.Interactive/KernelExtension.fs
=> Updated versions for formatting

Sources/AngouriMath/AngouriMath/Functions/Evaluation/Evaluation.Continuous/Evaluation.Continuous.Trigonometry.Classes.cs, Sources/Tests/UnitTests/PatternsTest/TrigTest.cs
=> Tan bug fixed

CHANGELOG.md
=> Fixed link for changelog (#528)
